### ISSUE TITLE
Detect fails with an error if no Cargo.lock or Cargo.toml

### ISSUE THREAD

**Issue by bchatelard** [paketo-community/cargo-install#91]
Detect fails with an error if no Cargo.lock or Cargo.toml and exit with a code 21.

```
...
===> DETECTING
[detector] ======== Output: paketo-community/cargo-install@0.0.9 ========
[detector] Missing [Cargo.toml: true, Cargo.lock: true], both required
[detector] err:  paketo-community/cargo-install@0.0.9 (1)
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: failed to detect: buildpack(s) failed with err
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 21
```

If I remove `packeto-comunity/rust` from the `order` in the builder.toml, it exit with a code 20.

```
===> DETECTING
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: Please check that you are running against the correct path.
[detector] ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 20
```

I am not sure why, is it required to wrap the error with `packit.Fail` to mute the error during detection ?

https://github.com/paketo-buildpacks/go-mod-vendor/blob/main/detect.go#L27

**Comment by dmikusa-pivotal** [comment]
Can you expand on the problem here? What's the `pack build` command you're running? Can you share anything about the app you're running or provide a demo?

The short answer is that the buildpack looks for those files because they're required to run `cargo install`. What is your use case where Cargo.toml & Cargo.lock are missing? 

Thanks

**Comment by bchatelard** [comment]
Hey, the use case is to be able to use a single `builder` to build all kind of apps (python, node, or rust).
If I try to build an empty project, the detect phase works fine with a 20 error code, except when I add the `packeto-community/rust` buildpack.

Here is how to reproduce:
https://gist.github.com/bchatelard/fd245a0a4f94187ef9bcc6ad043057ae

Create a custom builder (packeto full + packeto-community/python + packeto-community/rust).

```
pack builder create custom-builder --config builder.toml
```

```
mkdir /tmp/empty-project
cd /tmp/empty-project
pack build empty-project -b custom-builder
```

Try removing the rust in the repo and you dont have the same behaviour.

**Comment by dmikusa-pivotal** [comment]
Oh, ok. I follow now. That is an issue I've hit and something I'm going to be changing. I'm doing some work on the cargo-install buildpack as I write this and that fix should be part of the workstream. I can't give you a definitive date on when that'll be ready, but I'm hoping I'll have it all sorted in a couple of weeks. 

If you need an immediate fix, I think you can just change `packit.Fail.WithMessage("go.mod file is not present")` on the line you highlight to `nil`. I think that should cause it to fail, but not error. Then run the `./scripts/package.sh` script to package up your own copy of the buildpack.

**Comment by bchatelard** [comment]
Thanks, I just pushed a PR to fix this, I think it should works as expected.
